%hidden MODULE_NAME="clock"

set -g @catppuccin_clock_icon "\U000f0150 "
set -g @catppuccin_status_clock_icon_bg '#{@thm_lavender}'
set -g @catppuccin_status_clock_text_fg '#{E:@thm_fg}'
set -g @catppuccin_status_clock_text_bg '#{E:@catppuccin_status_module_text_bg}'
set -g @catppuccin_clock_text ' #{l:#{time_local}} #{l:#{time_zones}}'

source-file -q "$HOME/.tmux/plugins/tmux/utils/status_module.conf"
