%hidden MODULE_NAME="disk"

set -g @catppuccin_disk_icon "\U000f02ca "
set -g @catppuccin_status_disk_icon_bg '#{@thm_peach}'
set -g @catppuccin_status_disk_text_fg '#{E:@thm_fg}'
set -g @catppuccin_status_disk_text_bg '#{E:@catppuccin_status_module_text_bg}'
set -g @catppuccin_disk_text ' #{l:#{disk_fg_color}}#{l:#{disk_percentage}}'

source-file -q "$HOME/.tmux/plugins/tmux/utils/status_module.conf"
