%hidden MODULE_NAME="net"

set -g @catppuccin_net_icon "\U000f0318 "
set -g @catppuccin_status_net_icon_bg '#{@thm_sky}'
set -g @catppuccin_status_net_text_fg '#{E:@thm_fg}'
set -g @catppuccin_status_net_text_bg '#{E:@catppuccin_status_module_text_bg}'
set -g @catppuccin_net_text ' #{l:#{net_fg_color}}#{l:#{net_download}} #{l:#{net_upload}}'

source-file -q "$HOME/.tmux/plugins/tmux/utils/status_module.conf"
