%hidden MODULE_NAME="system"

set -g @catppuccin_system_icon "\U000f0a07 "
set -g @catppuccin_status_system_icon_bg '#{@thm_green}'
set -g @catppuccin_status_system_text_fg '#{E:@thm_fg}'
set -g @catppuccin_status_system_text_bg '#{E:@catppuccin_status_module_text_bg}'
set -g @catppuccin_system_text ' #{l:#{cpu_fg_color}}#{l:#{cpu_percentage}}#[fg=#{@thm_overlay_0}]/#{l:#{cpu_temp_fg_color}}#{l:#{cpu_temp}} #[fg=#{@thm_fg}]#{l:#{gpu_fg_color}}#{l:#{gpu_percentage}}#[fg=#{@thm_overlay_0}]/#{l:#{gpu_temp_fg_color}}#{l:#{gpu_temp}} #[fg=#{@thm_fg}]#{l:#{ram_fg_color}}#{l:#{ram_percentage}} #[fg=#{@thm_fg}]#{l:#{ram_swap_color}}#{l:#{ram_swap}} #[fg=#{@thm_fg}]#{l:#{disk_fg_color}}#{l:#{disk_percentage}}#[fg=#{@thm_fg}]#{l:#{battery_percentage}}'

source-file -q "$HOME/.tmux/plugins/tmux/utils/status_module.conf"
