%hidden MODULE_NAME="weather"

set -g @catppuccin_weather_icon "\U000f0595 "
set -g @catppuccin_status_weather_icon_bg '#{@thm_yellow}'
set -g @catppuccin_status_weather_text_fg '#{E:@thm_fg}'
set -g @catppuccin_status_weather_text_bg '#{E:@catppuccin_status_module_text_bg}'
set -g @catppuccin_weather_text ' #{l:#{weather_color}}#{l:#{weather_temp}}#[fg=#{@thm_fg}]#{l:#{weather_umbrella}}'

source-file -q "$HOME/.tmux/plugins/tmux/utils/status_module.conf"
