---
extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Document start
  document-start: disable

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Comments
  comments:
    min-spaces-from-content: 1

  # Empty lines
  empty-lines:
    max: 2

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

