tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "neomutt/neomutt"
tap "universal-ctags/universal-ctags"
brew "asciinema"
brew "awscli"
brew "bash"
brew "cmake"
brew "coreutils"
brew "curl"
brew "findutils"
brew "git"
brew "gnupg"
brew "htop"
brew "lynx"
brew "mas"
brew "moreutils"
brew "neofetch"
brew "neovim"
brew "node"
brew "python"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "tmux"
brew "urlview"
brew "vim"
brew "wget"
brew "whalebrew"
brew "zsh"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "android-studio"
cask "authy"
cask "balenaetcher"
cask "bartender"
cask "cleanmymac"
cask "coconutbattery"
cask "dbeaver-community"
cask "docker"
cask "dropbox"
cask "evolv-escribe-suite"
cask "firefox"
cask "flixtools"
cask "folx"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "handbrake"
cask "insomnia"
cask "intel-power-gadget"
cask "istat-menus"
cask "itau"
cask "iterm2"
cask "java"
cask "keka"
cask "keybase"
cask "lastpass"
cask "macvim"
cask "plex-media-server"
cask "robo-3t"
cask "sizeup"
cask "skype"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "tor-browser"
cask "transmission"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
mas "Amphetamine", id: 937984704
mas "CleanMyDrive 2", id: 523620159
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
