tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "neomutt/neomutt"
tap "universal-ctags/universal-ctags"
brew "ack"
brew "asciinema"
brew "awscli"
brew "bash"
brew "binutils"
brew "binwalk"
brew "cifer"
brew "cmake"
brew "coreutils"
brew "dex2jar"
brew "dns2tcp"
brew "fcrackzip"
brew "findutils"
brew "foremost"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "hashpump"
brew "helm"
brew "hydra"
brew "imagemagick"
brew "john"
brew "jq"
brew "knock"
brew "kubectl"
brew "lynx"
brew "mas"
brew "moreutils"
brew "mosh"
brew "neomutt"
brew "nmap"
brew "node@16", link: true
brew "openssl"
brew "p7zip"
brew "pigz"
brew "pngcheck"
brew "pv"
brew "python", link: true
brew "reattach-to-user-namespace"
brew "rename"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "socat"
brew "sqlite3"
brew "sqlmap"
brew "tmux"
brew "tree"
brew "ucspi-tcp"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "urlview"
brew "vim"
brew "webkit2png"
brew "wget"
brew "xpdf"
brew "zopfli"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "bartender" if `uname -m`.strip == "x86_64"
cask "cleanmymac"
cask "coconutbattery"
cask "dbeaver-community"
cask "docker"
cask "drivedx" if `uname -m`.strip == "x86_64"
cask "dropbox" if `uname -m`.strip == "x86_64"
cask "dropbox-beta" if `uname -m`.strip == "arm64"
cask "firefox"
cask "flixtools"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "insomnia"
cask "intel-power-gadget" if `uname -m`.strip == "x86_64"
cask "istat-menus"
cask "iterm2"
cask "keka"
cask "paragon-ntfs" if `uname -m`.strip == "x86_64"
cask "robo-3t"
cask "slack"
cask "spotify"
cask "transmission"
cask "tunnelblick"
cask "ultimaker-cura" if `uname -m`.strip == "x86_64"
cask "utm" if `uname -m`.strip == "arm64"
cask "virtualbox" if `uname -m`.strip == "x86_64"
cask "virtualbox-extension-pack" if `uname -m`.strip == "x86_64"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Disk Speed Test", id: 425264550
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
