
[manager]
ratio = [1, 4, 3]

sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 200

[preview]
tab_size = 4
max_width = 800
max_height = 600
cache_dir = "/tmp"
image_filter = "lanczos3"
image_quality = 80
sixel_fraction = 15

[preview.ueberzug_specific]
ueberzug_scale = 0.5
ueberzug_offset = [0.5, 0.5, -0.5, -0.5]
