---
# Lazydocker - https://github.com/jesseduffield/lazydocker
# On macOS: ~/Library/Application Support/jesseduffield/lazydocker

gui:
  scrollHeight: 2
  scrollPastBottom: true
  showAllContainers: false
  returnImmediately: false
  wrapMainPanel: true
  showBottomLine: true
  expandFocusedSidePanel: false
  screenMode: normal
  border: rounded
  theme:
    lightTheme: false
    activeBorderColor:
      - '#7aa2f7'
      - bold
    inactiveBorderColor:
      - '#414868'
    selectedLineBgColor:
      - '#283457'
    optionsTextColor:
      - '#7aa2f7'

logs:
  timestamps: true
  since: 60m

commandTemplates:
  dockerCompose: docker compose
  restartService: '{{ .DockerCompose }} restart {{ .Service.Name }}'
  stopService: '{{ .DockerCompose }} stop {{ .Service.Name }}'
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  viewServiceLogs: '{{ .DockerCompose }} logs --follow {{ .Service.Name }} | less +F'
  rebuildService: '{{ .DockerCompose }} up -d --build {{ .Service.Name }}'

oS:
  openCommand: open {{filename}}

reporting: "off"
