# Glances - https://glances.readthedocs.io
# Symlinked to ~/.config/glances/glances.conf

[global]
check_update=false
refresh=2

[quicklook]
disable=false
percentage_char=#

[cpu]
disable=false
iowait_careful=50
iowait_warning=70
iowait_critical=90
steal_careful=50
steal_warning=70
steal_critical=90

[percpu]
disable=true

[gpu]
disable=false

[mem]
disable=false
careful=50
warning=70
critical=90

[memswap]
disable=false
careful=50
warning=70
critical=90

[load]
disable=false
careful=0.7
warning=1.0
critical=5.0

[network]
disable=false
rx_careful=70
rx_warning=80
rx_critical=90
tx_careful=70
tx_warning=80
tx_critical=90
hide=lo,docker.*,veth.*,br-.*

[ip]
disable=false

[diskio]
disable=false
hide=loop.*,dm-.*

[fs]
disable=false
careful=50
warning=70
critical=90
hide=/dev/loop.*,/snap/.*,tmpfs

[irq]
disable=true

[folders]
disable=true

[raid]
disable=true

[sensors]
disable=false

[processcount]
disable=false

[processlist]
disable=false
sort_key=cpu_percent
min_user_filter_len=3
nice_warning=-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1

[ports]
disable=true

[docker]
disable=false

[amps]
disable=true

[connections]
disable=true

[wifi]
disable=false

[battery]
disable=false
careful=80
warning=90
critical=95
