################################################################################
# Registry
################################################################################
npmRegistryServer: "https://registry.npmjs.org/"

################################################################################
# Auth
################################################################################
npmAuthToken: "${NPM_TOKEN}"
npmAlwaysAuth: true

################################################################################
# Security
################################################################################
enableNetwork: true
enableTelemetry: false
auditLevel: moderate

################################################################################
# Network
################################################################################
httpTimeout: 60000
httpRetry: 3

################################################################################
# Performance
################################################################################
enableGlobalCache: true
enableImmutableInstalls: false

################################################################################
# Behavior
################################################################################
preferInteractive: false
progress: false
