# Yarn Configuration
# Maintains same behavior as .npmrc for consistency

# Registry configuration
npmRegistryServer: "https://registry.npmjs.org/"

# Authentication
npmAuthToken: "${NPM_TOKEN}"
npmAlwaysAuth: true

# Security settings
enableNetwork: true
enableTelemetry: false

# Audit settings (equivalent to npm audit)
auditLevel: moderate

# Network settings
httpTimeout: 60000
httpRetry: 3

# Performance settings
enableGlobalCache: true
enableImmutableInstalls: false

# CLI behavior
preferInteractive: false
progress: false
