################################################################################
# Settings
################################################################################
# Enable true colors
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Enable mouse
set-option -g mouse on

# Increase repeat time for repeatable commands
set -g repeat-time 1000

# Start window index at 1 instead of 0
set -g base-index 1

# Start pane index at 1 instead of 0
set-window-option -g pane-base-index 1

# Re-number windows when one is closed
set -g renumber-windows on

# Use vim key bindings
set-window-option -g mode-keys vi

# Automatically set window title
set-option -g allow-rename off
set-option -g set-titles on
set-option -g status-position bottom
set-window-option -g automatic-rename on

# Shut up, tmux
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

################################################################################
# Plugins
################################################################################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
  set -g @scroll-speed-num-lines-per-scroll "1"
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
  set -g @resurrect-strategy-vim 'session'
  set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-continuum'
  set -g @continuum-restore 'on'
set -g @plugin 'egel/tmux-gruvbox'
  set -g @tmux-gruvbox 'dark'

################################################################################
# TPM
################################################################################
run '~/.tmux/plugins/tpm/tpm'
