#!/usr/bin/env bash

################################################################################
# General aliases
################################################################################
# Always create parent folders if needed
command -v mkdir > /dev/null && alias mkdir="command mkdir -p -v"

# Use neomutt when available
command -v neomutt > /dev/null && alias mutt="command neomutt"

# FZF with bat preview
command -v fzf > /dev/null && command -v bat > /dev/null && alias fzf="command fzf --preview 'command bat --color=never --style=numbers --line-range=:500 {}'"

# TTY Clock with custom options
command -v tty-clock > /dev/null && alias tty-clock="command tty-clock -Dcs"

# Find files
command -v find > /dev/null && alias findf="command find . -type f -name"

# Find directories
command -v find > /dev/null && alias findd="command find . -type d -name"

################################################################################
# System specific aliases
################################################################################
case "$(uname)" in
  "Linux")
    # Colorized ls
    command -v ls > /dev/null && alias ls="command ls --color"

    # List all files colorized in long format, excluding . and ..
    command -v ls > /dev/null && alias la="command ls -lAF --color"

    # List only directories
    command -v ls > /dev/null && alias ld="command ls -lF --color | command grep --color=never '^d'"

    # Colorized grep
    command -v grep > /dev/null && alias grep="command grep --color"

    # GNU find aliases (Linux always has GNU)
    command -v find > /dev/null && alias findx="command find . -type f -executable"

    # GNU time aliases (Linux always has GNU)
    command -v time > /dev/null && alias time="command time -v"

    # GNU which aliases (Linux always has GNU)
    command -v which > /dev/null && alias which="command which -a"

    # Lock the screen (when going AFK)
    command -v gnome-screensaver-command > /dev/null || alias afk="gnome-screensaver-command --lock"

    # Browser
    command -v google-chrome > /dev/null || alias chrome="/opt/google/chrome/google-chrome"

    ;;
  "Darwin")
    if command ls --color > /dev/null 2>&1; then
      # GNU ls with color
      command -v ls > /dev/null && alias ls="command ls --color"

      # GNU ls with long format and color
      command -v ls > /dev/null && alias la="command ls -lAF --color"

      # GNU ls with long format and color, excluding directories
      command -v ls > /dev/null && alias ld="command ls -lF --color | grep --color=never '^d'"
    else
      # BSD ls with color
      command -v ls > /dev/null && alias ls="command ls -G"

      # BSD ls with long format and color
      command -v ls > /dev/null && alias la="command ls -lAF -G"

      # BSD ls with long format and color, excluding directories
      command -v ls > /dev/null && alias ld="command ls -lF -G | grep --color=never '^d'"
    fi

    if command find --version > /dev/null 2>&1; then
      # GNU find with executable flag
      command -v find > /dev/null && alias findx="command find . -type f -executable"
    else
      # BSD find with permission flag
      command -v find > /dev/null && alias findx="command find . -type f -perm +111"
    fi

    # Detect if time supports --version (GNU) or not (BSD)
    if command time --version > /dev/null 2>&1; then
      command -v time > /dev/null && alias time="command time -v"
    fi

    if command which --version > /dev/null 2>&1; then
      # GNU which with all instances
      command -v which > /dev/null && alias which="command which -a"
    fi

    if command grep --version > /dev/null 2>&1; then
      # GNU grep with color
      command -v grep > /dev/null && alias grep="command grep --color"
    else
      # BSD grep with color
      command -v grep > /dev/null && alias grep="command grep -G"
    fi

    # macOS has no `md5sum`, so use `md5` as a fallback
    command -v md5sum > /dev/null || alias md5sum="command md5"

    # macOS has no `sha1sum`, so use `shasum` as a fallback
    command -v sha1sum > /dev/null || alias sha1sum="command shasum"

    ;;
esac
