#!/usr/bin/env bash

################################################################################
# Normalize
################################################################################
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then
  # GNU `ls`
  colorflag="--color"
  export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else
  # macOS `ls`
  colorflag="-G"
  export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

################################################################################
# General aliases
################################################################################
# Always use color output for `ls`
alias ls="command ls --color"

# List all files colorized in long format, excluding . and ..
alias la="ls -lAF ${colorflag}"

# List only directories
alias ld="ls -lF ${colorflag} | grep --color=never '^d'"

# Always create parent folders if needed
alias mkdir="mkdir -p -v"

# Use neomutt when available
command -v neomutt > /dev/null || alias mutt="neomutt"

################################################################################
# System specific aliases
################################################################################
case "$(uname)" in
  "Linux")
    # Lock the screen (when going AFK)
    command -v gnome-screensaver-command > /dev/null || alias afk="gnome-screensaver-command --lock"

    # Browser
    command -v google-chrome > /dev/null || alias chrome="/opt/google/chrome/google-chrome"

    ;;
  "Darwin")
    # macOS has no `md5sum`, so use `md5` as a fallback
    alias md5sum="md5"

    # macOS has no `sha1sum`, so use `shasum` as a fallback
    alias sha1sum="shasum"

    # Use bat as previewer
    alias fzf="fzf --preview \"bat --color=always --style=numbers --line-range=:500 {}\""

    ;;
esac
