#!/usr/bin/env bash

################################################################################
# Internal functions to calculate the cores, memory and disk size for VMs
################################################################################
function __calculate_vm_cores() {
  case "$(uname -s)" in
    Darwin)

      echo $(( $(sysctl -n hw.ncpu) / 2 ))
      ;;
    Linux)
      echo $(( $(nproc) / 2 ))

      ;;
  esac
}

function __calculate_vm_memory() {
  case "$(uname -s)" in
    Darwin)

      echo $(( $(sysctl -n hw.memsize) / 1024 / 1024 / 1024 / 2 ))
      ;;
    Linux)
      echo $(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 1024 / 1024 / 2 ))

      ;;
  esac
}

function __calculate_vm_disk() {
  case "$(uname -s)" in
      Darwin)
        echo $(( $(df -g / | awk 'NR==2 {print $2}') / 20 ))

        ;;
      Linux)
        echo $(( $(df -BG / | awk 'NR==2 {gsub("G","",$2); print $2}') / 20 ))

        ;;
    esac
}

################################################################################
# Colima VM
################################################################################
function colima-start() {
  local cores="$(__calculate_vm_cores)"
  local memory="$(__calculate_vm_memory)"
  local disk="$(__calculate_vm_disk)"

  colima start \
    --cpu "${cores}" \
    --memory "${memory}" \
    --disk "${disk}" \
    \
    --runtime "docker" \
    --vm-type "qemu" \
    --mount "$HOME:w" \
    --dns "1.1.1.1,8.8.8.8"
}

function colima-stop() {
  colima stop
}

function colima-purge() {
  docker-purge

  colima stop --force
  colima delete --force
}

################################################################################
# Docker purge
################################################################################
function docker-purge() {
  docker stop $(docker ps -aq) 2>/dev/null
  docker rm -f $(docker ps -aq) 2>/dev/null
  docker rmi -f $(docker images -aq) 2>/dev/null
  docker volume rm $(docker volume ls -q) 2>/dev/null
  docker network rm $(docker network ls -q) 2>/dev/null
  docker builder prune -af
  docker system prune -af --volumes
}

################################################################################
# Mongo
################################################################################
function mongo-init() {
  mkdir -p "$HOME/Docker/Mongo"

  docker run \
    --detach \
    --hostname mongo \
    --name mongo \
    --restart unless-stopped \
    --env "MONGO_INITDB_ROOT_USERNAME=mongo" \
    --env "MONGO_INITDB_ROOT_PASSWORD=mongo" \
    --mount "type=bind,source=$HOME/Docker/Mongo,target=/external" \
    --publish "127.0.0.1:27017:27017" \
    mongo:latest
}

function mongo-start() {
  docker run mongo
}

function mongo-stop() {
  docker stop mongo
}

function mongo-purge() {
  mongo-stop
  docker rm mongo
  rm -rf "$HOME/Docker/Mongo"
}

function mongo-terminal() {
  docker exec -it mongo /bin/bash
}

################################################################################
# Postgres
################################################################################
function postgres-init() {
  mkdir -p "$HOME/Docker/Postgres"

  docker run \
    --detach \
    --hostname postgres \
    --name postgres \
    --restart unless-stopped \
    --env "POSTGRES_USER=postgres" \
    --env "POSTGRES_PASSWORD=postgres" \
    --mount "type=bind,source=$HOME/Docker/Postgres,target=/external" \
    --publish "127.0.0.1:5432:5432" \
    postgres:alpine
}

function postgres-start() {
  docker run postgres
}

function postgres-stop() {
  docker stop postgres
}

function postgres-purge() {
  postgres-stop
  docker rm postgres
  rm -rf "$HOME/Docker/Postgres"
}

function postgres-terminal() {
  docker exec -it postgres /bin/sh
}

################################################################################
# Redis
################################################################################
function redis-init() {
  mkdir -p "$HOME/Docker/Redis"

  docker run \
    --detach \
    --hostname redis \
    --name redis \
    --restart unless-stopped \
    --mount "type=bind,source=$HOME/Docker/Redis,target=/external" \
    --publish "127.0.0.1:6379:6379" \
    redis:alpine
}

function redis-start() {
  docker run redis
}

function redis-stop() {
  docker stop redis
}

function redis-purge() {
  redis-stop
  docker rm redis
  rm -rf "$HOME/Docker/Redis"
}

function redis-terminal() {
  docker exec -it redis /bin/sh
}

################################################################################
# Valkey
################################################################################
function valkey-init() {
  mkdir -p "$HOME/Docker/Valkey"

  docker run \
    --detach \
    --hostname valkey \
    --name valkey \
    --restart unless-stopped \
    --mount "type=bind,source=$HOME/Docker/Valkey,target=/external" \
    --publish "127.0.0.1:7000:7000" \
    valkey:alpine
}

function valkey-start() {
  docker run valkey
}

function valkey-stop() {
  docker stop valkey
}

function valkey-purge() {
  valkey-stop
  docker rm valkey
  rm -rf "$HOME/Docker/Valkey"
}

function valkey-terminal() {
  docker exec -it valkey /bin/sh
}

################################################################################
# Redict
################################################################################
function redict-init() {
  mkdir -p "$HOME/Docker/Redict"

  docker run \
    --detach \
    --hostname redict \
    --name redict \
    --restart unless-stopped \
    --mount "type=bind,source=$HOME/Docker/Redict,target=/external" \
    --publish "127.0.0.1:6379:6379" \
    registry.redict.io/redict:alpine
}

function redict-start() {
  docker run redict
}

function redict-stop() {
  docker stop redict
}

function redict-purge() {
  redict-stop
  docker rm redict
  rm -rf "$HOME/Docker/Redict"
}

function redict-terminal() {
  docker exec -it redict /bin/sh
}
