#!/usr/bin/env bash

################################################################################
# Define the platform docker should use
################################################################################
function get_platform() {
  case "$(uname -m)" in
    "arm64")
      echo "linux/arm64"

      ;;
    "x86_64")
      echo "linux/amd64"

      ;;
  esac
}

################################################################################
# Mongo
################################################################################
function mongo-init() {
  mkdir -p ~/Docker/Mongo

  docker run \
    --platform "$(get_platform)" \
    --detach \
    --hostname mongo \
    --name mongo \
    --restart unless-stopped \
    --env "MONGO_INITDB_ROOT_USERNAME=mongo" \
    --env "MONGO_INITDB_ROOT_PASSWORD=mongo" \
    --mount type=bind,source="$HOME"/Docker/Mongo,target=/external \
    --publish 127.0.0.1:27017:27017 \
    mongo:7
}

function mongo-start() {
  docker run mongo
}

function mongo-stop() {
  docker stop mongo
}

function mongo-purge() {
  mongo-stop
  docker rm mongo
  rm -rf ~/Docker/Mongo
}

function mongo-terminal() {
  docker exec -it mongo /bin/bash
}

################################################################################
# Postgres
################################################################################
function postgres-init() {
  mkdir -p ~/Docker/Postgres

  docker run \
    --platform "$(get_platform)" \
    --detach \
    --hostname postgres \
    --name postgres \
    --restart unless-stopped \
    --env "POSTGRES_USER=postgres" \
    --env "POSTGRES_PASSWORD=postgres" \
    --mount type=bind,source="$HOME"/Docker/Postgres,target=/external \
    --publish 127.0.0.1:5432:5432 \
    postgres:15-alpine
}

function postgres-start() {
  docker run postgres
}

function postgres-stop() {
  docker stop postgres
}

function postgres-purge() {
  postgres-stop
  docker rm postgres
  rm -rf ~/Docker/Postgres
}

function postgres-terminal() {
  docker exec -it postgres /bin/sh
}

################################################################################
# Redis
################################################################################
function redis-init() {
  mkdir -p ~/Docker/Redis

  docker run \
    --platform "$(get_platform)" \
    --detach \
    --hostname redis \
    --name redis \
    --restart unless-stopped \
    --mount type=bind,source="$HOME"/Docker/Redis,target=/external \
    --publish 127.0.0.1:6379:6379 \
    redis:7-alpine
}

function redis-start() {
  docker run redis
}

function redis-stop() {
  docker stop redis
}

function redis-purge() {
  redis-stop
  docker rm redis
  rm -rf ~/Docker/Redis
}

function redis-terminal() {
  docker exec -it redis /bin/sh
}
