#!/usr/bin/env bash

################################################################################
# Paths
################################################################################
case "$(uname)" in
  "Linux")
    export PATH="/usr/libexec/neomutt:$PATH"

    ;;
  "Darwin")
    case "$(uname -m)" in
      "arm64")
        export HOMEBREW_PREFIX="/opt/homebrew";
        export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
        export HOMEBREW_REPOSITORY="/opt/homebrew";
        export HOMEBREW_SHELLENV_PREFIX="/opt/homebrew";
        export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
        export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

        ;;
      "x86_64" | "Power Macintosh")
        export HOMEBREW_PREFIX="/usr/local";
        export HOMEBREW_CELLAR="/usr/local/Cellar";
        export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
        export HOMEBREW_SHELLENV_PREFIX="/usr/local";
        export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}";
        export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/usr/local/share/info:${INFOPATH:-}";

        ;;
    esac

    # cURL
    # shellcheck disable=SC2155
    export PATH="$(brew --prefix)/opt/curl/bin:$PATH"

    # OpenSSL
    # shellcheck disable=SC2155
    export PATH="$(brew --prefix)/opt/openssl/bin:$PATH"

    # Ruby
    # shellcheck disable=SC2155
    export PATH="$(brew --prefix)/opt/ruby/bin:$PATH"

    # NVM
    export NVM_DIR="$HOME/.nvm"
    # shellcheck disable=SC1091
    source "$(brew --prefix)/opt/nvm/nvm.sh"

    # Pnpm
    export PNPM_HOME="$HOME/Library/pnpm"
    export PATH="$PNPM_HOME:$PATH"

    # Android SDK
    export ANDROID_HOME="$HOME/Library/Android/sdk"
    # shellcheck disable=SC2155
    export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$(brew --prefix)/opt/openjdk@11/bin:$PATH"

    # Chruby
    source "$(brew --prefix)/opt/chruby/share/chruby/chruby.sh"
    source "$(brew --prefix)/opt/chruby/share/chruby/auto.sh"

    # Bc
    # shellcheck disable=SC2155
    export PATH="$(brew --prefix)/opt/bc/bin:$PATH"

    # Coreutils
    # shellcheck disable=SC2155
    export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"

    # Gawk
    # shellcheck disable=SC2155
    export PATH="$(brew --prefix)/opt/gawk/libexec/gnubin:$PATH"

    # GNU Sed
    # shellcheck disable=SC2155
    export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"

    ;;
esac
