#!/usr/bin/env bash

################################################################################
# Paths
################################################################################
case "$(uname)" in
  "Linux")
    export PATH="/usr/libexec/neomutt:$PATH"

    ;;
  "Darwin")
    case "$(uname -m)" in
      "arm64")
        export HOMEBREW_PREFIX="/opt/homebrew";
        export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
        export HOMEBREW_REPOSITORY="/opt/homebrew";
        export HOMEBREW_SHELLENV_PREFIX="/opt/homebrew";
        export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
        export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

        ;;
      "x86_64")
        export HOMEBREW_PREFIX="/usr/local";
        export HOMEBREW_CELLAR="/usr/local/Cellar";
        export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
        export HOMEBREW_SHELLENV_PREFIX="/usr/local";
        export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}";
        export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/usr/local/share/info:${INFOPATH:-}";

        ;;
    esac

    # cURL
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/curl/bin:$PATH"

    # OpenSSL
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/openssl/bin:$PATH"

    # Ruby
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/ruby/bin:$PATH"

    # NVM
    export NVM_DIR="$HOME/.nvm"
    # shellcheck disable=SC1091
    source "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"

    # Pnpm
    export PNPM_HOME="$HOME/Library/pnpm"
    export PATH="$PNPM_HOME:$PATH"

    # Android SDK
    export ANDROID_HOME="$HOME/Library/Android/sdk"
    # shellcheck disable=SC2155
    export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$HOMEBREW_PREFIX/opt/openjdk@11/bin:$PATH"

    # Chruby
    source "$HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh"
    source "$HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh"

    # Bc
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/bc/bin:$PATH"

    # Coreutils
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"

    # Gawk
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/gawk/libexec/gnubin:$PATH"

    # GNU Sed
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH"

    # GNU findutils
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/findutils/libexec/gnubin:$PATH"

    # GNU grep
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/grep/libexec/gnubin:$PATH"

    # GNU binutils
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/binutils/bin:$PATH"

    # GNU make
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$PATH"

    # GNU tar
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"

    # GNU which
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/which/bin:$PATH"

    # GNU diffutils
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/diffutils/bin:$PATH"

    # GNU patch
    # shellcheck disable=SC2155
    export PATH="$HOMEBREW_PREFIX/opt/patch/bin:$PATH"

    ;;
esac
