#!/usr/bin/env bash

################################################################################
# General paths
################################################################################
# NVM
if [ -d "$HOME/.nvm" ] || [ -h "$HOME/.nvm" ]; then
  export NVM_DIR="$HOME/.nvm"

  source "$NVM_DIR/nvm.sh"
fi

################################################################################
# System specific paths
################################################################################
case "$(uname)" in
  "Linux")
    export PATH="/usr/libexec/neomutt:$PATH"

    ;;
  "Darwin")
    case "$(uname -m)" in
      "arm64")
        export HOMEBREW_PREFIX="/opt/homebrew";
        export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
        export HOMEBREW_REPOSITORY="/opt/homebrew";
        export HOMEBREW_SHELLENV_PREFIX="/opt/homebrew";
        export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
        export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

        ;;
      "x86_64")
        export HOMEBREW_PREFIX="/usr/local";
        export HOMEBREW_CELLAR="/usr/local/Cellar";
        export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
        export HOMEBREW_SHELLENV_PREFIX="/usr/local";
        export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}";
        export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}:";
        export INFOPATH="/usr/local/share/info:${INFOPATH:-}";

        ;;
    esac

    export PATH="$(brew --prefix)/opt/curl/bin:$PATH"
    export PATH="$(brew --prefix)/opt/openssl/bin:$PATH"
    export PATH="$(brew --prefix)/opt/ruby/bin:$PATH"

    ;;
esac
