#!/usr/bin/env bash

################################################################################
# System specific paths
################################################################################
case "$(uname)" in
  Linux)
    # Flutter
    export PATH="$HOME/.flutter-sdk/bin:$PATH"

  ;;
  Darwin)
    # coreutils
    export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

    # findutils
    export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"

    # cURL
    export PATH="/usr/local/opt/curl/bin:$PATH"

    # OpenSSL
    export PATH="/usr/local/opt/openssl/bin:$PATH"

    # Python
    export PATH="$HOME/Library/Python/3.7/bin:$PATH"

    # Ruby
    export PATH="/usr/local/opt/ruby/bin:$PATH"
  ;;
esac

# Node.js
export PATH="$HOME/.global-modules/bin:$PATH"
