#!/usr/bin/env bash

################################################################################
# System specific settings
################################################################################
case "$(uname)" in
  "Linux")

    ;;
  "Darwin")
    # Zsh
    export ZSH_DISABLE_COMPFIX=true

    # Homebrew
    export HOMEBREW_NO_ANALYTICS=1
    export HOMEBREW_NO_ENV_HINTS=1

    # Docker
    export DOCKER_DEFAULT_PLATFORM=linux/amd64

    # Chruby
    source "$(brew --prefix)/opt/chruby/share/chruby/chruby.sh"
    source "$(brew --prefix)/opt/chruby/share/chruby/auto.sh"

    ;;
esac

################################################################################
# Shell
################################################################################
export HISTCONTROL=ignoredups
export HISTIGNORE="cd:ls:[bf]g:clear:exit"
export LANG=pt_BR.UTF-8

################################################################################
# Oh-my-zsh
################################################################################
export ZSH=~/.oh-my-zsh
export ZSH_THEME="spaceship"
export DISABLE_AUTO_UPDATE="true"
export HIST_STAMPS="dd/mm/yyyy"
export plugins=(
  gpg-agent
  ssh-agent
  tmux
)

################################################################################
# Spaceship
################################################################################
export SPACESHIP_USER_SHOW=always
export SPACESHIP_PROMPT_ADD_NEWLINE=false
export SPACESHIP_CHAR_SYMBOL="❯"
export SPACESHIP_CHAR_SUFFIX=" "
